services:
  web:
    build: .
    container_name: django-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - PORT=8080
    volumes:
      - .:/app
    command: gunicorn config.wsgi --bind 0.0.0.0:8080 --workers 3