services:
  web:
    build: .
    container_name: django-app
    ports:
      - "${HOST_PORT:-8080}:${CONTAINER_PORT:-8080}"
    env_file:
      - .env
    environment:
      - PORT=${CONTAINER_PORT:-8080}
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    command: >
      sh -c "python manage.py migrate &&
      gunicorn config.wsgi --bind 0.0.0.0:${PORT:-8080} --workers ${WORKERS:-3}"
    restart: unless-stopped

volumes:
  static_volume:
  media_volume: